version: '3.8'

services:
  # Serviço 1: Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: arch_db
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arch_studio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço 2: MinIO (Storage) - TEM QUE ESTAR ALINHADO COM O 'postgres'
  minio:
    image: minio/minio:latest
    container_name: arch_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000" # API (Java usa essa)
      - "9001:9001" # Console (Navegador usa essa)
    volumes:
      - minio_data:/data

volumes:
  postgres_data: garbo-ambientes-planejados_postgres_data
  minio_data: